config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    resources :comments 
  end
  get 'welcome/index'
  get "mierdo", to: "welcome#index"
  root 'welcome#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	validates :title, presence:true, uniqueness: true
	validates :body, presence:true, length: { minimum: 20}
	#validates :name, format:{ with: /Expresion Regular/ }
	before_create :set_visits_count

	def set_visits_count
		self.visits_count = 0
	end
	def update_visits_count
		if self.visits_count.nil? 
			self.set_visits_count
		end
		self.update(visits_count: self.visits_count + 1)
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/models/user0.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 before_action :authenticate_user!, except: [:show, :index]
 before_action :set_article, only: [:destroy, :show]
 
 def index
   @articles = Article.all
 end

 def show
 	@article.update_visits_count
 	@comment = Comment.new
 end

 def new
 	@article= Article.new 	
 end

 def create
 	@article = current_user.articles.new( title:params[:article][:title],
 	body:params[:article][:body])
 	if @article.save then
 	  redirect_to @article
 	else
 	  render :new
 	end
 end

 def destroy
  	@article.destroy
 	redirect_to articles_path
 end

 def set_article	
 	@article = Article.find(params[:id])
 end

 def update
	
 end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = current_user.comments.new(comment_params)
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end

    def set_article
      @article = Article.find(params[:article_id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<% @articles.each do |article| %> 

<div class="article-show-index">
	<h3><%=article.title %></h3>
	<p><%=article.body %></p>
	<button ><%= link_to "Mostrar", article_path(article) %>
	</button>
</div>

<%end%>

<%= link_to "Crear articulo", new_article_path(@articles), :class => "new-article-button-index" %>

app/views/articles/new.html.erb
<h1>Crear Articulo</h1> 
<div style:"padding=1.2em">
<% @article.errors.full_messages.each do |e|%>
<p class="error-new-article">
  <%=e %>
</p>
<% end -%>
	<%= form_for(@article) do |f| %>
		<div class="field">
			<%= f.text_field :title, placeholder:"Titulo"%>
		</div>
		<div class="field">
			<%= f.text_field :body, placeholder:"Escribe aqui tu Articulo" %>
		</div>
		<div class="field">
			<%= f.submit "Guardar"%>
		</div>
		<% end %>
</div>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p><%= @article.body %></p>

<p>Numero de visitas: <%= @article.visits_count %></p>

<% unless @article.user.nil? %>
	<p>Escrito por: <%=@article.user.email %></p>
<%end -%>

<h4>Comentarios</h4>

<% @article.comments.each_with_index do |comment, i| %>
	<p> #<%=i+1 %> => <%= comment.body %> </p>
	<hr>
<% end -%>
<%= render 'comments/form'  %>
<p><%= link_to "Eliminar", @article, method: :delete %></p>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tester</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
    <header id="header" class="clearfix" role="banner">
    
        <hgroup>
            <h1 id="site-title"><a href="index.html">A HTML5 Theme</a></h1>
            <h2 id="site-description">This is an awesome description of the site!</h2>
        </hgroup>
    
    </header> <!-- #header -->

<div id="main" class="clearfix">

	<!-- Navigation -->
    <nav id="menu" class="clearfix" role="navigation">
        <ul> 
            <li class="current">
            	<%= link_to "Inicio", root_path %>
            </li>
            <li>
                <%= link_to "Articulos", articles_path %>
                <ul>
                    <li><a href="#">Subpage</a></li>
                    <li><a href="#">Subpage 2</a></li>
                </ul>
            </li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
        <%if user_signed_in? %>
        <%= link_to "Cerrar Sesion de  #{current_user.email}", destroy_user_session_path, method: :delete %>
        <% end -%>

    </nav> <!-- #nav -->
 

<%= yield %>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Testeeeer</h1>
<p>Find me in app/views/welcome/index.html.erb</p>